/** Modules **/
export { ActorModule } from './actor'
export { CarouselModule } from './carousel'
export { EpisodeModule } from './episode'
export { FileModule } from './file'
export { FilmModule } from './film'
export { ManagementModule } from './management'
export { PosterModule } from './poster'
export { SeasonModule } from './season'
export { SerieModule } from './serie'
export { StoryboardModule } from './storyboard'
export { SubtitleModule } from './subtitle'
export { ThumbnailModule } from './thumbnail'
export { TrailerModule } from './trailer'
export { UserModule } from './user'
export { BackdropModule } from './backdrop'

/** Controllers **/
export { ActorController } from './actor/controller'
export { CarouselController } from './carousel/controller'
export { EpisodeController } from './episode/controller'
export { FileController } from './file/controller'
export { FilmController } from './film/controller'
export { ManagementController } from './management/controller'
export { PosterController } from './poster/controller'
export { SeasonController } from './season/controller'
export { SerieController } from './serie/controller'
export { StoryboardController } from './storyboard/controller'
export { SubtitleController } from './subtitle/controller'
export { ThumbnailController } from './thumbnail/controller'
export { TrailerController } from './trailer/controller'
export { UserController } from './user/controller'
export { BackdropController } from './backdrop/controller'

/** Services **/
export { ActorService } from './actor/service'
export { CarouselService } from './carousel/service'
export { EpisodeService } from './episode/service'
export { FileService } from './file/service'
export { FilmService } from './film/service'
export { ManagementService } from './management/service'
export { PosterService } from './poster/service'
export { SeasonService } from './season/service'
export { SerieService } from './serie/service'
export { StoryboardService } from './storyboard/service'
export { SubtitleService } from './subtitle/service'
export { ThumbnailService } from './thumbnail/service'
export { TrailerService } from './trailer/service'
export { UserService } from './user/service'
export { BackdropService } from './backdrop/service'