export const APIKEY_TMDB = '70614e303dc8033e590dee7680485ccd'
export const ROOT_TMDB = 'https://api.themoviedb.org/3'
export const ROOT_IMAGES_TMDB_500 = 'https://image.tmdb.org/t/p/w500'
export const ROOT_IMAGES_TMDB_ORIGINAL = 'https://image.tmdb.org/t/p/original'
export const ROOT_YTDL = 'https://www.youtube.com/watch?v='
export const ROOT_YTEMBED = 'https://www.youtube.com/embed/'
